PYTHON = python
FLASK_APP = main.py
REQUIREMENTS_FILE = requirements.txt

# Targets
.PHONY: run install clean

run:
	$(PYTHON) $(FLASK_APP)

install:
	$(PYTHON) -m pip install -r $(REQUIREMENTS_FILE)

clean:
	# Add any cleanup tasks here

